networks:
  internal:
    name: internal
    external: false

volumes:
  bitcoin-data:
    driver: local
  electrs-data:
    driver: local
  ord-data:
    driver: local

services:
  bitcoin:
    image: ruimarinho/bitcoin-core:24-alpine
    restart: unless-stopped
    ports:
      - 18443:18443
    volumes:
      - bitcoin-data:/home/bitcoin/.bitcoin
    networks:
      - internal
    command: -printtoconsole
      -txindex=1
      -regtest=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=${BITCOIN_USER}
      -rpcpassword=${BITCOIN_PASSWORD}
      -fallbackfee=0.00001
    healthcheck:
      test: bitcoin-cli -regtest -rpcuser=${BITCOIN_USER} -rpcpassword=${BITCOIN_PASSWORD} getrpcinfo
      interval: 5s
      timeout: 5s
      retries: 3

  ordinals-ord:
    image: haffjjj/ordinals-ord:v0.18.4
    restart: unless-stopped
    ports:
      - 3032:3032
    volumes:
      - ord-data:/root/.local/share
    depends_on:
      bitcoin:
        condition: service_healthy
    networks:
      - internal
    command: --chain=regtest
      --bitcoin-rpc-url=http://bitcoin:18443
      --bitcoin-rpc-username=${BITCOIN_USER}
      --bitcoin-rpc-password=${BITCOIN_PASSWORD}
      --index-sats
      --index-runes
      server
      --http-port=3032
    healthcheck:
      test: curl -f localhost:3032/blockheight || exit 1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3

  blockstream-electrs:
    image: haffjjj/blockstream-electrs:v1.0.0
    restart: unless-stopped
    ports:
      - 3002:3002 # rest api
      - 60401:60401 # electrum
    volumes:
      - electrs-data:/data/db
    depends_on:
      bitcoin:
        condition: service_healthy
    networks:
      - internal
    command: -vvvv
      --jsonrpc-import
      --network=regtest
      --daemon-rpc-addr=bitcoin:18443
      --cookie=${BITCOIN_USER}:${BITCOIN_PASSWORD}
      --lightmode=1
      --index-unspendables=1
      --utxos-limit=100000
      --electrum-txs-limit=100000
      --http-addr=0.0.0.0:3002
      --electrum-rpc-addr=0.0.0.0:60401
    healthcheck:
      test: curl -f localhost:3002/mempool || exit 1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3

  janoside-btc-rpc-explorer:
    image: haffjjj/janoside-btc-rpc-explorer:v3.4.0
    restart: unless-stopped
    ports:
      - 3000:3002
    depends_on:
      bitcoin:
        condition: service_healthy
      blockstream-electrs:
        condition: service_healthy
    networks:
      - internal
    environment:
      BTCEXP_HOST: 0.0.0.0
      BTCEXP_PORT: 3002
      BTCEXP_BITCOIND_URI: bitcoin://${BITCOIN_USER}:${BITCOIN_PASSWORD}@bitcoin:18443?timeout=10000
      BTCEXP_ADDRESS_API: electrum
      BTCEXP_ELECTRUM_SERVERS: tcp://blockstream-electrs:60401
      BTCEXP_ELECTRUM_TXINDEX: true
